---

- name: FIXME
  hosts: [ 'debops_service_ROLE_NAME' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: ROLE_OWNER.ROLE_NAME
      tags: [ 'role::ROLE_NAME' ]
