---

- name: Manage disks
  hosts: [ 'ypid_service_disk' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: aeriscloud.disk
      tags: [ 'role::disk' ]
