---

- name: Configure dnsmasq client on a Qubes OS TemplateBasedVM with minimal dependencies
  hosts: [ 'debops_service_dnsmasq_qubes_os_min' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.dnsmasq
      tags: [ 'role::dnsmasq' ]

    - role: debops.persistent_paths
      tags: [ 'role::persistent_paths' ]
      persistent_paths__dependent_paths: '{{ dnsmasq__persistent_paths__dependent_paths }}'
