---

- name: Common configuration for all hosts
  hosts: [ 'ypid_common', 'ypid_service_packages' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::packages', 'role::apt_preferences' ]

    - role: ypid.packages
      tags: [ 'role::packages', 'role::packages:only' ]
