---

- name: Manage updatedb Debian-like systems
  hosts: [ 'ypid_common' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: tersmitten.updatedb
      tags: [ 'role::updatedb' ]
