---

- name: Common configuration for all hosts
  hosts: 'all:!ypid_no_common'
  become: True

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::packages', 'role::apt_preferences' ]

    - role: ypid.packages
      tags: [ 'role::packages' ]

    ## Merge move to debops.rsyslog and debops.logrotate
    # - role: ypid.rsyslog
    #   tags: [ 'role::ypid.rsyslog' ]

    - role: ypid.kernel_module
      tags: [ 'role::kernel_module' ]

    - role: tersmitten.updatedb
      tags: [ 'role::updatedb' ]

    - role: ypid.divert
      tags: [ 'role::divert' ]

    - role: ypid.copy
      tags: [ 'role::copy' ]
