---

- name: Prepare core environment
  hosts: [ 'debops_all_hosts_minimum', '!debops_no_common' ]
  become: False

  roles:

    - role: debops.core
      tags: [ 'role::core' ]
      become: True

- name: Common configuration for all hosts
  hosts: [ 'debops_all_hosts_minimum', '!debops_no_common' ]
  gather_facts: True
  become: True

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ sshd__apt_preferences__dependent_list }}'
        - '{{ apt__apt_preferences__dependent_list }}'
        - '{{ apt_install__apt_preferences__dependent_list }}'

    - role: debops.apt
      tags: [ 'role::apt' ]

    - role: debops.apt_install
      tags: [ 'role::apt_install' ]

    - role: debops.etc_services
      tags: [ 'role::etc_services' ]

    - role: debops.atd
      tags: [ 'role::atd' ]

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ ntp_ferm_dependent_rules|d([]) }}'
        - '{{ postfix_ferm_dependent_rules|d([]) }}'
        - '{{ sshd__ferm__dependent_rules|d([]) }}'

    - role: debops.tcpwrappers
      tags: [ 'role::tcpwrappers' ]
      tcpwrappers_dependent_allow:
        - '{{ sshd__tcpwrappers__dependent_allow }}'

    - role: debops.ntp
      tags: [ 'role::ntp' ]

    - role: debops.ifupdown
      tags: [ 'role::ifupdown' ]

    - role: debops.console
      tags: [ 'role::console' ]

    - role: debops.rsyslog
      tags: [ 'role::rsyslog' ]

    - role: debops.unattended_upgrades
      tags: [ 'role::unattended_upgrades' ]

    - role: debops.users
      tags: [ 'role::users' ]

    - role: debops.sshkeys
      tags: [ 'role::sshkeys' ]

    - role: debops.sshd
      tags: [ 'role::sshd' ]

    - role: debops.resources
      tags: [ 'role::resources' ]
