---

- name: Show host groups
  hosts: [ 'all' ]
  ## Don’t require network access.
  gather_facts: False
  become: False

  tasks:

    - name: Show host groups
      debug:
        msg: '{{ hostvars[inventory_hostname]["group_names"] | sort }}'
