---

- name: Put /etc under version control using etckeeper
  hosts: [ 'debops_service_etckeeper_early' ]
  become: True

  roles:

    - role: debops-contrib.etckeeper
      tags: [ 'role::etckeeper' ]
