---

- name: Ensure specified packages are in there desired state
  apt:
    name: '{{ item }}'
    state: '{{ "latest" if (x2go_server__deploy_state == "present") else "absent" }}'
    install_recommends: False
    purge: True
  with_flattened: '{{ x2go_server__base_packages }}'
  tags: [ 'role::x2go_server:pkts' ]
